POST  http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "mario",
    "email": "mar@gmail.com",
    "password": "mar123456",
    "c_password": "mar123456"
}

### login


POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "mar@gmail.com",
    "password": "mar123456"
    
}

### perfil 
GET http://127.0.0.1:8000/api/user
Accept: application/json
Authorization: Bearer 31|YsRk3LxgA666UajworJR50WcTZUvEjR776YhyKAW4c82d66a

### perfil 2 
GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Authorization: Bearer 9|Sr1GyBY8LcYmE5jAk9ef2UScJ6ilRPw5LAVxOwav63492834


### logout
POST  http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 10|1wP9R9BGA5HieHLOTvpS2vugSvgaRaFUNS2TCoqca7eed3c9