POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@mail.com",
    "password": "admin54321",
    "c_password": "admin54321"
}

### login

POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

### Perfil
GET http://127.0.0.1:8000/api/user
Accept: application/json
Authorization: Bearer 1|yE1RNDrnBfLzGTqe6aNy5MMrs4LjMSuoa3nHuMgx22267809

### Perfil 2
GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Authorization: Bearer 32|cEVdZt4VwDiNu8EAA3bSVXtC5oFwmNjW5FFpthiF

### Logout
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 6|RGG4lpvBxlJdb6X3T0epe6tOJsq5B9NF4VeY1R6t

